version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hgk_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hgk_network

  web:
    build: .
    container_name: hgk_web
    command: >
      sh -c "
        echo 'Waiting for db...' &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo 'Database is ready!' &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn project.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - project/.env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - hgk_network

  nginx:
    image: nginx:stable-alpine
    container_name: hgk_nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    restart: unless-stopped
    networks:
      - hgk_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  hgk_network: